### ISSUE TITLE
The evaluation strategy should be specified

### ISSUE THREAD

**Issue by gasche** [MaiaVictor/caramel#2]
I missed two important information from your otherwise very nice README. Apologies if they are hidden somewhere and I didn't look closely enough -- but maybe they should be more visible, then.
- What does it mean to "evaluate" in your system? Do you compute a full normal form (this is what I understand from the example), or maybe a head normal form or weak head normal form?
- How is this evaluation implemented (by, for example, a reduction strategy). Is your implementation rather call-by-value, call-by-name, something else? This would be useful to reason about the performance of various ways to write the same program.

**Comment by VictorTaelin** [comment]
You are right. I didn't specify the reduction strategy on the README because Caramel isn't supposed - at least for now - to run complex programs. The original idea was to evaluate you programs to normal form and then compile them to run somewhere else, be it your own λ-calculator or a programming language such as Haskell, Scheme or JavaScript. Ideally, you'd compile just the logic, avoiding huge numbers, using the native Ints/etc on the target language instead. The implementation is very simple and naive - it is the `reduce` function on [src/Lambda.hs](https://github.com/MaiaVictor/caramel/blob/master/src/Lambda.hs) - which you can easily hack into another strategy yourself. It currently reduces the leftmost innermost redex, even inside abstractions, i.e., the applicative order reduction to normal form. That means the full normal form is reached, and that any term containing a term without normal form will fail to halt (thus, the Y combinator is simply not useable right now!).

That said, I'm a lot interested in better reduction strategies in general and my other project, [Optlam](https://github.com/maiavictor/optlam), investigates a technique for optimal reductions, which involves compiling lambda-calculus expressions to/from a new computation model called interaction nets. It is very interesting and has a series of cool results, for example, being able to reduce programs that couldn't be reduced with a [computer the size of the universe](http://stackoverflow.com/questions/31707614/why-are-λ-calculus-optimal-evaluators-able-to-compute-big-modular-exponentiation) if we used conventional strategies. There are some open problems too, though - but once those ideas mature I'd probably bring it to Caramel.

**Comment by gasche** [comment]
Thanks for your detailed answer.

If your planned use is, as you describe, driving partial evaluation/specialization/meta-generation of a codebase that is otherwise externally meaningful (in another language), then (first you should maybe state it somewhere in the README and second) it is important that you explicitly specify that you are computing a full normal form -- in particular reducing under lambdas.

**Comment by VictorTaelin** [comment]
I agree, I've added a statement on the Example section of the README. Do you think it is clearer now? I also added transmogrifiers so you can run Caramel programs in several different λ-calculus implementations (considering any language with high-order functions as an implementation).

(You still need to exclude the Y-combinators on recursive programs, adding them (if you really, really need it) after compilation.)

**Comment by gasche** [comment]
Indeed, the added mention is fine. I'll close the issue, given that the other part (the evaluation strategy) will surely change over time and you seem to have creative ideas of what to do there. Thanks for the interesting discussion and project!
